name: dayo
description: A new Flutter project.

version: 1.0.5

environment:
  sdk: ">=2.2.0 <3.0.0"

# 依赖库
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.0.0
  cookie_jar: ^3.0.0-beta2
  cupertino_icons: ^1.0.2
  date_format: ^2.0.2
  devicelocale: ^0.4.2
  dio: ^4.0.0-beta7
  dio_cookie_manager: ^2.0.0-beta1
  extended_image: ^4.0.1
  event_bus: ^2.0.0
  flutter_easyrefresh: ^2.1.6
  flutter_spinkit: ^5.0.0
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.11
  flutter_xupdate: ^2.0.2
  get: 4.1.4
  # image_picker_saver: ^0.3.0
  oktoast: ^3.0.0
  path_provider: ^2.0.1
  package_info: ^2.0.0
  permission_handler: ^7.1.0
  provider: ^5.0.0
  shared_preferences: ^2.0.3
  share: ^2.0.1
  url_launcher: ^6.0.2
  date_range_picker: ^1.0.5
  amap_flutter_location: ^3.0.0
  webview_flutter: ^1.0.7
  image_picker: ^0.7.1
  jpush_flutter: 2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# 字体、图标、图片等资源加载
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/image/main_bg_blue.png
  - assets/image/main_bg_yellow.png
  - assets/image/main_bg_red.png
  - assets/image/main_icon_bfjy.png
  - assets/image/main_icon_clff.png
  - assets/image/main_icon_ddzx.png
  - assets/image/main_avatar.png
  - assets/image/main_bmyzq.png
  - assets/image/main_title_func.png
  - assets/image/main_top_bg.png
  - assets/image/wb_scgl.png
  - assets/image/wb_jzdd.png
  - assets/image/wb_ddgl.png
  - assets/image/wb_qjbx.png
  - assets/image/wb_ywzs.png
  - assets/image/wb_xyxdu.png
  - assets/image/wb_lcyq.png
  - assets/image/wb_jkh5.png
  - assets/image/my_dqbb.png
  - assets/image/my_sjtj.png
  - assets/image/my_ysxy.png
  - assets/image/my_xgmm.png
  - assets/image/my_zftj.png
  - assets/image/my_bg.png
  - assets/image/my_right.png
  - assets/image/bg.png
  - assets/image/login_bg.png
  - assets/image/logo.png
  - assets/image/wb_qrssp.png
  - assets/image/wb_rxsjpd.png


  fonts:
    - family: xuifont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  
        